
ALTER TABLE Teams REBUILD WITH (IGNORE_DUP_KEY = ON)
:r .\dbo.Teams.Table.sql
GO
ALTER TABLE Teams REBUILD WITH (IGNORE_DUP_KEY = OFF)

ALTER TABLE Users REBUILD WITH (IGNORE_DUP_KEY = ON)
:r .\dbo.Users.Table.sql
GO
ALTER TABLE Users REBUILD WITH (IGNORE_DUP_KEY = OFF)

ALTER TABLE Users_In_Teams REBUILD WITH (IGNORE_DUP_KEY = ON)
:r .\dbo.Users_In_Teams.Table.sql
GO
ALTER TABLE Users_In_Teams REBUILD WITH (IGNORE_DUP_KEY = OFF)